handlers=java.util.logging.ConsoleHandler
.level=SEVERE

# Reduce noisy Java language server logs
org.eclipse.lsp4j.level=SEVERE
org.eclipse.lsp4j.jsonrpc.level=SEVERE
org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.level=SEVERE

# Reduce framework/plugin chatter inside the LS runtime
org.apache.aries.spifly.level=WARNING
com.microsoft.java.debug.plugin.level=WARNING
com.microsoft.java.debug.plugin.internal.JavaDebuggerServerPlugin.level=WARNING

java.util.logging.ConsoleHandler.level=SEVERE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
